steps:
  - id: "Docker"
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', '${_IMAGE_NAME}', '--build-arg', 'ADO_BASE64_PAT_TOKEN=${_ADO_BASE64_PAT_TOKEN}', '--build-arg', 'SOURCE_BRANCH_NAME=${_SOURCE_BRANCH_NAME}', '.' ]

substitutions:
  _IMAGE_NAME: '${_GCP_ARTIFACT_REPO}/sched-rag-svc:${TAG_NAME}'
options:
  dynamic_substitutions: true
images:
  - '${_IMAGE_NAME}'
